---

### `app/pubspec.yaml`
```yaml
name: willa_ia
description: Super assistente pessoal IA Geral – Willa Suprema
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.6
  provider: ^6.0.5
  flutter_dotenv: ^5.0.2
  speech_to_text: ^6.3.0
  flutter_tts: ^3.6.3

dev_dependencies:
  flutter_test:
    sdk: flutter
